AIRTABLE_API_KEY="patBR3NWcLJEmpfdi.46a9e32f6c6578333432f4e46d489c59fc5a85a4d2a4a7450ece5e7f173c8883"
AIRTABLE_BASE_ID="app2OPW0c5Pf72lAb"
OPENAI_API_KEY="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"